# -*- coding: utf-8 -*-
"""422(01).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xd-qKpYBB6el69IjMO7NUIAmGAk8lLnm
"""

x = input(" insert a percentage   ")
print (float(x.strip('%'))/100)

x = int(input(" insert centigrade "))
y = 1.8 * x + 32
print (y)

x = int(input(" insert inches "))
y = int(x/12)
z = x%12
print (y, "feet", z, "inches")

copyType1 = 50
copyType2 = 30
changeVariable = 100
x = int(input(" insert how many copy you want "))
if x <= changeVariable:
    print(x*copyType1)
else:
    y = x - changeVariable
    print (changeVariable*copyType1 + y*copyType2)

year = int(input())
is_leap = year % 4 == 0 and (year % 400 == 0 or year % 100 != 0)
if is_leap:
    print("it is a leap year mate")
else:
    print("it is not a leap year mate")

for x in range(1, 101):
    if x % 3 == 0:
        print (x, end= ",")

import cmath

year=1980
equation= (-1)**2-4*1*year
x = format((-1-cmath.sqrt(equation))/(2*1))
y = format((-1+cmath.sqrt(equation))/(2*1))
print(x,y)

x = [10,100,90,75,25,20]
openingIndex = 0 
lastIndex = -1
x.sort()
print(x)
print("problem1=", x[openingIndex] +x [lastIndex] )
print("problem2=", x[openingIndex + 1] + x[lastIndex -1] )
print("problem3=", x[openingIndex + 2] + x[lastIndex-2] )

x = [1,10,9,7,2,3,4,5,6,8]
x.sort()
avg = round(sum(x) / len(x)) 
small = x[0]
print("problem1=", avg - small )
large = x[-1]
print("problem2=", avg - large )

a = float(input(' 1 ')) 
b = float(input(' 2 ')) 
c = float(input(' 3 ')) 
s = (a + b + c) / 2  
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5  
print (area)









